
 The following SQL statements will be executed:

     CREATE TABLE news (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(100) NOT NULL, content VARCHAR(300) NOT NULL, image VARCHAR(20) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
     CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, uuid INT NOT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:json)', password VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_8D93D649D17F50A6 (uuid), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
