index:
    path: /
    controller: App\Controller\WebController::homepageAction

infantil:
  path: /infantil
  controller: App\Controller\SectionPageWithSectionsController:infantilAction

tabalers:
  path: /tabalers
  controller: App\Controller\SectionPageOnlyDescriptionController:tabalersAction

histrions:
  path: /histrions
  controller: App\Controller\SectionPageOnlyDescriptionController:histrionsAction

diables:
  path: /diables
  controller: App\Controller\SectionPageWithSectionsController:diablesAction

equip-permanent:
  path: /equip-permanent
  controller: App\Controller\EntitatController:equipPermanentAction

entitat:
  path: /entitat
  controller: App\Controller\EntitatController:entitatAction

correfoc:
  path: /correfoc
  controller: App\Controller\CorrefocController:correfocAction

correaigua:
  path: /correaigua
  controller: App\Controller\ActesController:correaiguaAction 

moscada-infantil:
  path: /moscada-infantil
  controller: App\Controller\ActesController:moscadaInfantilAction

bategada:
  path: /bategada
  controller: App\Controller\ActesController:bategadaAction

carnavalada:
  path: /carnavalada
  controller: App\Controller\ActesController:carnavaladaAction

trobada-diables:
  path: /trobada-diables
  controller: App\Controller\ActesController:trobadaDiablesAction

aixada:
  path: /aixada
  controller: App\Controller\ActesController:aixadaAction

passatge-terror:
  path: /passatge-terror
  controller: App\Controller\ActesController:passatgeTerrorAction