index:
    path: /
    controller: App\Controller\WebController::homepageAction

infantil:
  path: /infantil
  controller: App\Controller\SectionPageWithSectionsController:infantilAction

tabalers:
  path: /tabalers
  controller: App\Controller\SectionPageOnlyDescriptionController:tabalersAction

histrions:
  path: /histrions
  controller: App\Controller\SectionPageOnlyDescriptionController:histrionsAction

diables:
  path: /diables
  controller: App\Controller\SectionPageWithSectionsController:diablesAction

equip-permanent:
  path: /equip-permanent
  controller: App\Controller\EntitatController:equipPermanentAction

entitat:
  path: /entitat
  controller: App\Controller\EntitatController:entitatAction

correaigua:
  path: /correaigua
  controller: App\Controller\ActesController:correaiguaAction 

moscada-infantil:
  path: /moscada-infantil
  controller: App\Controller\ActesController:moscadaInfantilAction

bategada:
  path: /bategada
  controller: App\Controller\ActesController:bategadaAction

carnavalada:
  path: /carnavalada
  controller: App\Controller\ActesController:carnavaladaAction

trobada-diables:
  path: /trobada-diables
  controller: App\Controller\ActesController:trobadaDiablesAction

aixada:
  path: /aixada
  controller: App\Controller\ActesController:aixadaAction

passatge-terror:
  path: /passatge-terror
  controller: App\Controller\ActesController:passatgeTerrorAction

correfoc:
  path: /correfoc
  controller: App\Controller\CorrefocController:correfocAction

mostra:
  path: /mostra
  controller: App\Controller\CorrefocController:mostraAction

historia:
  path: /historia
  controller: App\Controller\CorrefocController:historiaAction

recorregut:
  path: /recorregut
  controller: App\Controller\CorrefocController:recorregutAction

dimonis:
  path: /dimonis
  controller: App\Controller\CorrefocController:dimonisAction

bestiari:
  path: /bestiari
  controller: App\Controller\CorrefocController:bestiariAction

figures:
  path: /figures
  controller: App\Controller\CorrefocController:figuresAction  

musica:
  path: /musica
  controller: App\Controller\CorrefocController:musicaAction

tabalers-correfoc:
  path: /tabalers-correfoc
  controller: App\Controller\CorrefocController:tabalersAction  

quants-band:
  path: /quants-band
  controller: App\Controller\CorrefocController:quantsbandAction  

sac:
  path: /sac
  controller: App\Controller\CorrefocController:sacAction

seguretat:
  path: /seguretat
  controller: App\Controller\CorrefocController:seguretatAction

contacte:
  path: /contacte
  controller: App\Controller\ContacteController:contacteAction

agenda:
  path: /agenda
  controller: App\Controller\EntitatController:agendaAction