index:
    path: /
    controller: App\Controller\WebController::homepageAction

infantil:
  path: /infantil
  controller: App\Controller\SectionPageWithSectionsController:infantilAction

tabalers:
  path: /tabalers
  controller: App\Controller\SectionPageOnlyDescriptionController:tabalersAction

histrions:
  path: /histrions
  controller: App\Controller\SectionPageOnlyDescriptionController:histrionsAction